version = 1
merge.automerge_label = "ğŸš€  merge it ğŸš€"
require_automerge_label = true
merge.delete_branch_on_merge = true
merge.notify_on_conflict = true
merge.message.title = "pull_request_title"
merge.message.body = "empty"
merge.message.include_pr_number = true
merge.message.include_coauthors = true
update.ignored_usernames = ["dependabot-preview"]